services:
  postgres_social:
    container_name: postgres_social
    image: postgres:14
    environment:
      POSTGRES_USER: social
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: quarkus-social
    ports:
      - "5435:5432"